### ISSUE TITLE
Syntax Error: main.py line 239 (make sure the directory exists)

### ISSUE THREAD

**Issue by zenny** [C0D3D3V/Moodle_Downloader_2#10]
Hi,

I downloaded and installed the master branch with python 3.5.9 locally installed using asdf.

```
$ pip3 install -r requirements.txt --user
Collecting sentry_sdk>=0.13.5 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/8e/e6/058c2dc4723b3647a8cf61385c61f284bfbd0d0657bc5623c22e9ef45a3c/sentry_sdk-0.14.2-py2.py3-none-any.whl (96kB)
    100% |████████████████████████████████| 102kB 775kB/s 
Collecting cutie>=0.2.2 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/79/1d/f8389619189b3de32f66be40cc7d17d6d2c06e35bbd21f6869120bd912b3/cutie-0.2.2-py3-none-any.whl
Collecting colorama>=0.4.3 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl
Collecting urllib3>=1.10.0 (from sentry_sdk>=0.13.5->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl (125kB)
    100% |████████████████████████████████| 133kB 1.6MB/s 
Collecting certifi (from sentry_sdk>=0.13.5->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl (156kB)
    100% |████████████████████████████████| 163kB 1.8MB/s 
Collecting readchar (from cutie>=0.2.2->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/ef/f3/50cc9199733bf91f3c140150752a6430d8b785f9d22a31dcae721edb0b9a/readchar-2.0.1-py3-none-any.whl
Installing collected packages: urllib3, certifi, sentry-sdk, readchar, colorama, cutie
Successfully installed certifi-2019.11.28 colorama-0.4.3 cutie-0.2.2 readchar-2.0.1 sentry-sdk-0.14.2 urllib3-1.25.8
```

So far so good, but:

```
$ python3 main.py --init
  File "main.py", line 238
    f"'{path}' is not a valid path. Make sure the directory exists.")
                                                                   ^
SyntaxError: invalid syntax
```

Which directory is it asking for? And which {path} is it referring to?

Cheers!
/z

**Comment by C0D3D3V** [comment]
Which operating system do you use?

The error does not occur with me.

You could eventually solve the problem by specifying a valid path with the `--path` option, as it is explained in the Readme.

**Comment by C0D3D3V** [comment]
The requested path is the one where all files are downloaded and where the database and the configuration is currently located. Actually this should be the current working path (the path where you run the program).

**Comment by C0D3D3V** [comment]
Ah no, I see the problem now. 
Your Python version is too old. I used the syntax for format strings, which is only available since version 3.6.
I should update the version requirements or change the syntax.

**Comment by C0D3D3V** [comment]
I made a short update, maybe it works without updating your Python. Give it a try.

**Comment by zenny** [comment]
@C0D3D3V Thanks for the prompt response.

I tested with both versions (3.5.9 and 3.6.10) and both appears to work.

However, only part ((no videos, just a welcome audio from under week 2, fyi) got downloaded from the moodle instance in https://moocs.hes-so.ch 

Did I miss something?

**Comment by C0D3D3V** [comment]
Great, I'm glad!
The downloader currently only downloads files from courses you are enrolled in. Furthermore only normal files, links and assignment files as well as submissions are downloaded. 

Videos are special resources on moodle. I can deal with them after the exam phase so that they can be downloaded.

**Comment by zenny** [comment]
> Great, I'm glad!
> The downloader currently only downloads files from courses you are enrolled in. Furthermore only normal files, links and assignment files as well as submissions are downloaded. External links are only downloaded as links.
> 
> Videos are special resources on moodle. I can deal with them after the exam phase so that they can be downloaded.

Oh I see. 

The purpose of any offline course downloader gets defeated if multimedia are not downloaded.

However, I am sure you would soon realize the multimedia download feature as seen from your promptness and proactivity! Yay! Kudos!

Cheers,
/z

**Comment by C0D3D3V** [comment]
If you already need this function you can also test the old [downloader](https://github.com/C0D3D3V/Moodle-Downloader), it should have no problem with the videos, only with the file structure (but I can't promise it).


I will add the option to the new downloader in about two weeks.

**Comment by C0D3D3V** [comment]
I created an account on https://moocs.hes-so.ch and took a look at the situation. 
The videos were not uploaded directly to moodle but are hosted on youtube. So it wouldn't help to download the videos with my downloader. I have tested this once, on moodle there is only one html page saved with the embedded video, exactly this page is downloaded. 

To download youtube videos efficiently I would recommend jdownloader 2 or youtube-dl (two very popular and large projects), with appropriate plugins you can also feed them directly from the browser with links.

**Comment by zenny** [comment]
> I created an account on https://moocs.hes-so.ch and took a look at the situation.
> The videos were not uploaded directly to moodle but are hosted on youtube. So it wouldn't help to download the videos with my downloader. I have tested this once, on moodle there is only one html page saved with the embedded video, exactly this page is downloaded.
> 
> To download youtube videos efficiently I would recommend jdownloader 2 or youtube-dl (two very popular and large projects), with appropriate plugins you can also feed them directly from the browser with links.

Thanks for your prompt action to look in to the matter. Commendable! 

However, they have two locations of videos, youtube and tube.switch.ch. 

I used youtube-dl to download from youtube and video-downloader browser plugin to download from switch.

Thanks!
