### ISSUE TITLE
[Request] Also download submissions

### ISSUE THREAD

**Issue by SrSands** [C0D3D3V/Moodle_Downloader_2#11]
I have a couple of systems running the script and the only inconvenience i faced is that if i want to go back to the work that I hve made I have to manually download the files that i want.

Also it would be nice for example, to get to the end of a course, run the script and have an offline copy of all the work you have done, as well as all the files in case the page ever gets removed.

**Comment by SrSands** [comment]
I dint read all the documentations and got to the part were there is already an option to do exactly that. Sorry.
You should put it on the from readme for example.

**Comment by C0D3D3V** [comment]
Yes, sorry, I will soon add more information about how and what you can configure.
