### ISSUE TITLE
"python3 main.py --init" does nothing

### ISSUE THREAD

**Issue by artaeun** [C0D3D3V/Moodle_Downloader_2#13]
![image](https://user-images.githubusercontent.com/6439106/76209975-7379af80-6203-11ea-8037-5422d85660a5.png)
The command does not give any other messages or settings or anything, at all. 

All dependencies are satisfied, using python 3.8 (could this be the problem?) on windows 10

**Comment by C0D3D3V** [comment]
Interesting :/  no output at all is strange

maybe try `python` instead of `python3`

And please try the same in command prompt (https://www.howtogeek.com/235101/10-ways-to-open-the-command-prompt-in-windows-10/)

**Comment by artaeun** [comment]
The same was tried with command prompt.

Did not try with `python`, and it does work with it. Thanks!
