### ISSUE TITLE
[Enhancement] Consider removal of downloaded files in database

### ISSUE THREAD

**Issue by steelstrings** [C0D3D3V/Moodle_Downloader_2#14]
If you remove files, which you don't need (anymore) or by accident, the database could reflect this state.

If you want to download those files again, you can do so easily (without manually modifying the database).

You could argue that if you don't want to the keep those files at all, hence you don't want to download them, they will be downloaded anyways if the database tracks removed files. But then again I don't think this is a sensible use case.

**Comment by C0D3D3V** [comment]
It's designed the other way because we decided a long time ago in the old version of the Moodle Downloader that most people don't like the folder structure of Moodle. So we wanted to be able to move and rearrange the files ourselves and delete unnecessary files without having to download them again.

**Comment by C0D3D3V** [comment]
Additionally even files that have been deleted online are still tracked. This has no effect on the download behavior. This is only done to get a log of the files.

**Comment by C0D3D3V** [comment]
I can imagine to extend it to give you a list of files that are no longer available offline, but still online. And selected files, then get deleted from the database so that they can be downloaded again.

**Comment by C0D3D3V** [comment]
By the way, for manual editing of the database I would recommend the https://sqlitebrowser.org/.

**Comment by C0D3D3V** [comment]
Or do you have a better idea? I never actually had this case, so I don't have a very good idea. I can come up with the most blatant versioning system, but that would be off the mark. (By the way, that's exactly what you could do, you could put your download folder under versioning e.g. git). But maybe you have a good idea that would help you.

**Comment by shoeper** [comment]
Sounds like an option to download files missing on disk.

**Comment by C0D3D3V** [comment]
Check out the new Option `--manage-database`. It is just a basic manager, but it is ok for simple tasks.
