### ISSUE TITLE
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc3'

### ISSUE THREAD

**Issue by Kerouace** [C0D3D3V/Moodle_Downloader_2#24]
Hey, I came across a UnicodeEncodeError while using Moodle_Downloader_2.
```
Start downloading changed files...
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/app/moodle_downloader_2/download_service/downloader.py", line 61, in run
    self.state_recorder.save_file(
  File "/app/moodle_downloader_2/state_recorder/state_recorder.py", line 335, in save_file
    self.new_file(file, course_id, course_fullname)
  File "/app/moodle_downloader_2/state_recorder/state_recorder.py", line 346, in new_file
    cursor.execute("""INSERT INTO files
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc3' in position 11: surrogates not allowed
```

**Comment by C0D3D3V** [comment]
Looks like your Moodle has at least one invalid UTF-8 text which the downloader tries to store in the local database. I will think of a solution tomorrow. Either allow invalid UTF-8 or remove the affected characters, not sure which would be better.

**Comment by C0D3D3V** [comment]
Was this the first time you run the downloader?

**Comment by Kerouace** [comment]
It was the first time I tried to download all the Moodle courses.
I tried a lot today and I think the error was not caused by a Moodle entry with invalid UTF-8 characters.
The error seems to correlate with pressing arrow keys during renaming of courses.
I renamed all the courses in the config dialog and made a mistake.
I tried to use the arrow keys to navigate to the place of the typo.
This did not work and I deleted the name and rewrote it.
My guess is that a keystroke is still in the configuration.
So it might be useful to prevent such entries in the configuration dialog.

**Comment by C0D3D3V** [comment]
Ah thank you very much! This is very helpful. I'll try to prevent it.

**Comment by C0D3D3V** [comment]
Do you use Linux?

**Comment by Kerouace** [comment]
I use the python:3 docker image which is based on Debian.

**Comment by C0D3D3V** [comment]
Ah found the problem. Arrow keys should now working in input. But i can not prevent some complete strange utf-8 input, I have no idea how i could do this without dropping utf-8 support complete. 
There is a way to adjust the SQL-Lite cursor so that it drops invalid utf-8 characters, but for now this problem should be fixed. If such a problem occurs again I will take harder steps.  

I'm gonna push this to main tonight.

**Comment by Kerouace** [comment]
Thank you! I really appreciate your efforts.
