### ISSUE TITLE
Exception: 's'

### ISSUE THREAD

**Issue by SrSands** [C0D3D3V/Moodle_Downloader_2#3]
Looking at the logs I'm getting error in a lot of files:
`2020-01-15 10:15:13  ERROR  {download_service}  Error while trying to download file: [COURSE] -[File.pdf]! Exception: 's'`

Not sure why.
Also a option for saving the files in a specific location and not in the same folder as all the files would be awesome so I can have my files organized.

**Comment by SrSands** [comment]
Also I want to congrat you for your amazing code, super fast and easy to set up.
Not as full of options as the V1 but I know is an early state. :+1:

**Comment by C0D3D3V** [comment]
Thanks for your great feedback. 
Currently only normal files, folders, links and files in assignments are downloaded. If anything else is missing, you are welcome to create a new issue for that file type. 

Yes, there are still a few bugs that I am aware of but I try to fix them quickly. Soon the exam phase will start and then I don't have much time. 

I don't know why the exception is only an 's', but I'm working on it, as soon as I've fixed it I'll let you know, then we'll find out more about the bug. Currently it could be anything. 

I've updated the readme, maybe the `--path` option will now help you with your target location problem. You can re-sort and reorder all files in the target location, the downloader will not change anything once downloaded.

**Comment by SrSands** [comment]
> Soon the exam phase will start and then I don't have much time.

Yeah dont worry, take your time and good luck with your exams.

> I don't know why the exception is only an 's',

Me neither and seems strange because the file is a pdf not a strange file.The log look like this:

`2020-01-16 08:36:50  ERROR  {download_service}  Error while trying to download file: ./[Course name]/[Folder]/[File].pdf! Exception: 's'`

Its a normal pdf, not heavy and i can download it fine trough the browser.

**Comment by C0D3D3V** [comment]
I have fixed the problem with the exception: 's'. But there is still a problem with changed files. My state_recorder does not yet recognize correct if a file has been changed to moodle. i will try to fix this in the next days.

**Comment by C0D3D3V** [comment]
I fixed that too, so finaly there is no bug that I know...
