### ISSUE TITLE
/moodle\\login/token.php was not found on the server

### ISSUE THREAD

**Issue by ManoloZocco** [C0D3D3V/Moodle_Downloader_2#7]
Hi everyone, when I set up the moodle account i receive this errors:
`Error while communicating with the Moodle System! (An Unexpected Error happened on side of the Moodle System! Status-Code: 404
Header: [('Date', 'Wed, 19 Feb 2020 10:01:18 GMT'), ('Server', 'Apache/2.4.7 (Ubuntu)'), ('Content-Length', '304'), ('Content-Type', 'text/html; charset=iso-8859-1')]
Response: b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /moodle\\login/token.php was not found on this server.</p>\n<hr>\n<address>Apache/2.4.7 (Ubuntu) Server at elearning.unisi.it Port 443</address>\n</body></html>\n') Please try again.`

but as you can see the token.php page is on the server: https://elearning.unisi.it/moodle/login/token.php and in https://elearning.unisi.it/moodle//login/token.php

What can i do? can i manually extract the token and pass it to the software?
Thanks in advance!

**Comment by shoeper** [comment]
Have you configured moodle as location? Don't know the exact name but there is a setting for the path / location of moodle.

**Comment by C0D3D3V** [comment]
Interesting bug, but it works fine for me. 
Please try to use `https://elearning.unisi.it/moodle/` as URL of Moodle
```
URL of Moodle:   https://elearning.unisi.it/moodle/
Username for Moodle:   asd
Password for Moodle [no output]:   
Login Failed! (The Moodle System rejected the Request. Details: Login errato, riprova (Errorcode: invalidlogin, Stacktrace: None, Debuginfo: None, Reproductionlink: None)) Please try again.
```

If that doesn't work either, I can explain how you can get the token manually.

**Comment by ManoloZocco** [comment]
Thanks for the reply. I followed your instructions but I keep having the same error. I paste the exact procedure I do. I also checked the requirements.

`#path_to_MD2> pip3 install -r requirements.txt
Requirement already satisfied: sentry_sdk>=0.13.5 in c:\path\to\python\python37\lib\site-packages (from -r requirements.txt (line 1)) (0.14.1)
Requirement already satisfied: certifi in c:\path\to\python\python37\lib\site-packages (from sentry_sdk>=0.13.5->-r requirements.txt (line 1)) (2019.6.16)
Requirement already satisfied: urllib3>=1.10.0 in c:\path\to\python\python37\lib\site-packages (from sentry_sdk>=0.13.5->-r requirements.txt (line 1)) (1.25.3)

# path_to_MD2> python main.py --init
Do you want to override the existing config [y/n]?   y
Do you want to activate Notifications via mail [y/n]?   n
Do you want to configure Error Reporting via Sentry? [y/n]n
[The following Credentials are not saved, it is only used temporarily to generate a login token.]
URL of Moodle:   https://elearning.unisi.it/moodle/
Username for Moodle:   myuser.name
Password for Moodle [no output]:
Error while communicating with the Moodle System! (An Unexpected Error happened on side of the Moodle System! Status-Code: 404
Header: [('Date', 'Wed, 19 Feb 2020 13:29:36 GMT'), ('Server', 'Apache/2.4.7 (Ubuntu)'), ('Content-Length', '304'), ('Content-Type', 'text/html; charset=iso-8859-1')]
Response: b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /moodle\\login/token.php was not found on this server.</p>\n<hr>\n<address>Apache/2.4.7 (Ubuntu) Server at elearning.unisi.it Port 443</address>\n</body></html>\n') Please try again.
URL of Moodle:`

**Comment by C0D3D3V** [comment]
Ok, I could reproduce the bug now, it only exists under Windows. It doesn't occur under Linux. 
It doesn't help to generate the token manually. I'll do some testing and try to fix the bug quickly.

You could however try to generate a token and then create a config.json like I explained [here](https://github.com/C0D3D3V/Moodle_Downloader_2/issues/4#issuecomment-581629707)

To generate a token you need to visit this link: 
`https://www.yourmoodle.com/login/token.php?username=USERNAME&password=PASSWORD&service=moodle_mobile_app`

Replace `USERNAME` and `PASSWORD` with your username and password.

**Comment by ManoloZocco** [comment]
Generating the token, and putting the information in the json file, everything worked perfectly. Thanks so much!

**Comment by C0D3D3V** [comment]
I uploaded an update 49e5b4e0c76f8f4412bc7e9ad2dcc192ef243d3d. 
If you find any other bugs under windows, you are welcome to report them.
